######################
# HTTP Serverにアクセスしたい（ホストがアクセスできるようにポートのフォワーディング設定をする）
######################
# docker compose -f docker-compose-7-ok.yml up
######################
# ===別ターミナルにて(5秒くらい待って)===========================
# $ docker compose -f docker-compose-7-ng.yml exec server wget -nv localhost:8000
# 2024-07-17 08:47:55 URL:http://localhost:8000/ [13/13] -> "index.html" [1]
# $ wget -nv localhost:8000
# 2024-07-17 17:47:59 URL:http://localhost:8000/ [13/13] -> "index.html" [1]

services:
  server:
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile7
    ports: # ★
      - 8000:8000
